name       : libcangjie
version    : 1.3
release    : 1
source     :
    - https://github.com/Cangjians/libcangjie/releases/download/v1.3/libcangjie-1.3.tar.xz : f4b9a0cf8673f49adb22b675992360799d66eb8d5bce2bd603358de78509d30b
license    : LGPL-3.0
component  : desktop.library
summary    : This is a C library implementing the Cangjie input method.
description: |
    This is a C library implementing the Cangjie input method.
builddeps  :
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
